"""Declarative base and shared model conventions (F0.3.3).

Every domain entity in `docs/architecture/domain-model.md` extends `Model`, not
`Base` directly, so the primary-key and audit-column shape is uniform rather than
each new table reinventing it. `Base` alone (no id/timestamps) exists only because
Alembic's `target_metadata` needs a `DeclarativeBase` to introspect, independent of
which columns any concrete table carries.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import Uuid

# Recommended by the SQLAlchemy docs: without this, autogenerate invents
# constraint names from object ids, so the same model produces a different
# migration on every run. A fixed convention makes autogenerate deterministic.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Root of the declarative mapping. Its `.metadata` is Alembic's `target_metadata`."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Model(Base):
    """Abstract base every domain entity extends: a UUID key and audit timestamps.

    The id is generated by PostgreSQL's `gen_random_uuid()` — built into core since
    PG13, so the baseline migration (F0.3.4) enables `pgcrypto` for N1 encryption
    without needing a second extension for UUIDs. Generating server-side, rather
    than in Python, means the id exists even for rows inserted outside the ORM
    (bulk loads, seed SQL) and can't drift from what the database actually stored.

    `updated_at`'s `onupdate` fires on any ORM-issued UPDATE; a bulk `UPDATE`
    statement that bypasses the ORM does not trigger it.
    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
