#!/usr/bin/env python
"""Generate the BRD requirement-to-scenario traceability report (F0.6.4).

Maps every EARS requirement ID declared in the BRD to the Gherkin scenarios
tagged with it (`@A9`, not a pytest mark — see conftest's `pytest_bdd_apply_tag`).
Requirement IDs come from the BRD text itself, not a hardcoded list, so a
requirement the BRD adds or renumbers shows up here unmodified.

Usage:
    uv run python scripts/generate_brd_traceability.py > ../docs/planning/brd-traceability.md
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pytest_bdd.parser import FeatureParser

BACKEND_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = BACKEND_ROOT.parent
BRD_PATH = REPO_ROOT / "docs/requirements/ai-budget-agent-brd-v1.1.md"
FEATURES_DIR = BACKEND_ROOT / "tests/features"

BRD_REQUIREMENT_HEADING_RE = re.compile(r"\*\*([A-Z]\d{1,2})\s+\(")
TAG_SHAPED_LIKE_A_REQUIREMENT_ID_RE = re.compile(r"^[A-Z]\d{1,2}$")


def brd_requirement_ids() -> list[str]:
    """Every EARS requirement ID declared in the BRD, in document order."""
    text = BRD_PATH.read_text()
    ordered_unique: dict[str, None] = {}
    for match in BRD_REQUIREMENT_HEADING_RE.finditer(text):
        ordered_unique.setdefault(match.group(1), None)
    return list(ordered_unique)


def traced_scenarios_by_requirement() -> dict[str, list[tuple[str, str]]]:
    """requirement id -> [(feature path, scenario name), ...], read from the .feature files.

    Walks `tests/features/` recursively: each BR lives in its own directory
    alongside the test module and step definitions that run it, so the path
    rather than the bare filename is what identifies a scenario here.
    """
    mapping: dict[str, list[tuple[str, str]]] = {}
    for feature_file in sorted(FEATURES_DIR.rglob("*.feature")):
        feature = FeatureParser(str(feature_file.parent), feature_file.name).parse()
        relative_path = feature_file.relative_to(FEATURES_DIR).as_posix()
        for scenario in feature.scenarios.values():
            for tag in scenario.tags | feature.tags:
                if TAG_SHAPED_LIKE_A_REQUIREMENT_ID_RE.match(tag):
                    mapping.setdefault(tag, []).append((relative_path, scenario.name))
    return mapping


def build_report() -> str:
    """Render the full traceability report as markdown."""
    requirement_ids = brd_requirement_ids()
    traced = traced_scenarios_by_requirement()

    lines = [
        "# BRD requirement traceability",
        "",
        "Generated by `backend/scripts/generate_brd_traceability.py` (F0.6.4) — "
        "never edited by hand, regenerate it instead. Maps every EARS requirement ID "
        "in the BRD to the Gherkin scenarios tagged with it in `backend/tests/features/`.",
        "",
        "Being listed here means acceptance criteria exist for a requirement, not that "
        "they currently pass — most BR feature files are still wired up but skipped "
        "pending their owning epic (see that file's `tests/features/test_*.py` module).",
        "",
        "| Requirement | Scenarios |",
        "|---|---|",
    ]
    for requirement_id in requirement_ids:
        scenarios = traced.get(requirement_id, [])
        if scenarios:
            cell = "<br>".join(f"`{filename}`: {name}" for filename, name in scenarios)
        else:
            cell = "_Not yet traced by a scenario._"
        lines.append(f"| {requirement_id} | {cell} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    sys.stdout.write(build_report())


if __name__ == "__main__":
    main()
