/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report process liveness and database reachability.
         *
         *     Always 200: the process being able to respond at all is the liveness
         *     signal. `database.reachable` carries dependency health as data instead
         *     of conflating a downstream outage with the process itself being down.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Report the running build SHA and current receipt parser version (BRD A15).
         */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a new account and return it with a session (F1.1.3).
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate and return an access token (F1.1.4).
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a valid refresh token for a new session (F1.2.3).
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the given session (F1.2.3).
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Read current user profile (F1.4.1).
         */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Partially update user profile (F1.4.1).
         */
        patch: operations["update_me_users_me_patch"];
        trace?: never;
    };
    "/receipts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Receipt
         * @description Accept up to 10 photos or scans for a single receipt (F2.2).
         *
         *     Validates count (max 10) and total size (max 50MB) (BRD A4, A8).
         *     Validates that each uploaded file is a supported image or PDF (BRD A1, A2).
         *     Returns immediately with a tracking handle (F2.5).
         */
        post: operations["upload_receipt_receipts_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/upload/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Receipts Batch
         * @description Accept multiple receipts in one request (F2.3.1).
         *
         *     Each form field represents a distinct receipt. Its value must be a list of files.
         *     Limits (max 10 photos, max 50MB) are applied independently per receipt (BRD A5, A7, A8).
         *     Validates that each uploaded file is a supported image or PDF (BRD A1, A2).
         *     Returns immediately with a tracking handle (F2.5).
         */
        post: operations["upload_receipts_batch_receipts_upload_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/upload/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload Job Status
         * @description Query the status of an asynchronous upload job (F2.5.2).
         */
        get: operations["get_upload_job_status_receipts_upload__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/images/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Receipt Image
         * @description Redirects to a time-limited URL for the requested receipt image (F2.4.2).
         */
        get: operations["get_receipt_image_receipts_images__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/upload/{job_id}/resolve-duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Duplicate
         * @description Resolve a duplicate receipt detection by confirming or skipping (A14).
         */
        post: operations["resolve_duplicate_receipts_upload__job_id__resolve_duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/upload/{job_id}/resolve-position-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Position Match
         * @description Resolve a position match conflict by overriding the decision (BRD B7).
         */
        post: operations["resolve_position_match_receipts_upload__job_id__resolve_position_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/line-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Line Items
         * @description One page of the caller's line items, with what the whole selection costs (C3, C4, D1).
         */
        get: operations["list_line_items_receipts_line_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Receipts
         * @description List an account's stored receipts newest first with pagination (F3.8).
         */
        get: operations["list_receipts_receipts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Receipt
         * @description Get a receipt's detail including its line items (F3.8).
         */
        get: operations["get_receipt_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Receipt
         * @description Permanently delete a receipt together with its line items and photos.
         */
        delete: operations["delete_receipt_receipts__receipt_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Receipt
         * @description Correct a stored receipt's header and line items (F3.9, BRD A9, A11).
         */
        patch: operations["update_receipt_receipts__receipt_id__patch"];
        trace?: never;
    };
    "/receipts/upload/{job_id}/resolve-total": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Total
         * @description Resolve a missing or low-confidence total (F4.7).
         */
        post: operations["resolve_total_receipts_upload__job_id__resolve_total_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/upload/{job_id}/line-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Line Item
         * @description Correct a line item the parser misread, before the batch is stored (BRD A9).
         */
        post: operations["edit_line_item_receipts_upload__job_id__line_item_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/upload/{job_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Job
         * @description Commit all resolved extractions to the database (F4.7).
         */
        post: operations["commit_job_receipts_upload__job_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/line-items/{item_id}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Line Item Category
         * @description Reassign one line item to a category of the owner's choosing (BRD C4).
         */
        patch: operations["update_line_item_category_receipts_line_items__item_id__category_patch"];
        trace?: never;
    };
    "/receipts/{receipt_id}/categorise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recategorise Receipt
         * @description Re-run automatic categorisation on a stored receipt, sparing manual choices (C3, C4).
         */
        post: operations["recategorise_receipt_receipts__receipt_id__categorise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description List the taxonomy — built-in and custom — with this user's totals (BRD C1, C2).
         */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        /**
         * Create Category
         * @description Create a custom category, available to the picker and the agent at once (BRD C6).
         */
        post: operations["create_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Category
         * @description Delete one of the caller's categories, moving its items to `move_to_id` (BRD C7).
         */
        delete: operations["delete_category_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Category
         * @description Rename one of the caller's own categories (BRD C6).
         */
        patch: operations["rename_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/budget/months/{year}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Month Summary
         * @description The caller's spend in one calendar month, and what is held out of it (BRD D1-D5).
         *
         *     The client names the month and passes its own `today`: whether a month is
         *     still running depends on the user's clock, which only the browser knows
         *     (ADR-0009). Without it the server's UTC date stands in. A month that is over
         *     is served from its snapshot, taken on this first look (ADR-0010).
         */
        get: operations["get_month_summary_api_v1_budget_months__year___month__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthResponse
         * @description Response containing the authenticated user and their access token.
         */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** Body_upload_receipt_receipts_upload_post */
        Body_upload_receipt_receipts_upload_post: {
            /** Files */
            files: string[];
        };
        /**
         * CategoryCreate
         * @description A new custom category (BRD C6).
         */
        CategoryCreate: {
            /** Name */
            name: string;
        };
        /**
         * CategoryOut
         * @description A category with its aggregated statistics for the current user.
         */
        CategoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Builtin */
            is_builtin: boolean;
            /** Item Count */
            item_count: number;
            /** Total Amount */
            total_amount: string;
        };
        /** CategoryResponse */
        CategoryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * CategorySpendResponse
         * @description One category's share of the items on screen; `category_id` is null for none at all.
         */
        CategorySpendResponse: {
            /** Category Id */
            category_id: string | null;
            /** Name */
            name: string | null;
            /** Item Count */
            item_count: number;
            /** Total Amount */
            total_amount: string;
        };
        /**
         * CategoryUpdate
         * @description A new name for one of the user's own categories (BRD C6).
         */
        CategoryUpdate: {
            /** Name */
            name: string;
        };
        /**
         * CommitJobRequest
         * @description Request to commit selected extractions to the database.
         */
        CommitJobRequest: {
            /** Indices To Store */
            indices_to_store: number[];
        };
        /**
         * EditLineItemRequest
         * @description Correct one line item the parser misread, before anything is stored (BRD A9, A11).
         *
         *     Every field is optional and `None` means "leave it alone". An empty string is
         *     a real value meaning "there is no readable amount here", which is what the
         *     parser itself returns for a line it could not price — so the two cannot be
         *     collapsed. Callers must send only the fields they are changing.
         */
        EditLineItemRequest: {
            /** Extraction Index */
            extraction_index: number;
            /** Item Index */
            item_index: number;
            /** Name */
            name?: string | null;
            /** Quantity */
            quantity?: string | null;
            /** Unit Price */
            unit_price?: string | null;
            /** Total Price */
            total_price?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemView
         * @description The three lists on the categorisation screen (docs/design/screens/categorisation.html).
         *
         *     `needs_review` is the queue itself (C3); `corrected` is what the owner
         *     reassigned by hand (C4); `all` is every item they have.
         * @enum {string}
         */
        ItemView: "needs_review" | "corrected" | "all";
        /**
         * JobStatus
         * @description Lifecycle states of an asynchronous upload job.
         * @enum {string}
         */
        JobStatus: "pending" | "processing" | "completed" | "stored" | "failed";
        /**
         * LineItemInput
         * @description One line item in an `UpdateReceiptRequest`.
         *
         *     An existing line carries its `id`; a new line omits it. An existing id that
         *     is not resent is deleted, so the request represents the receipt's *entire*
         *     desired line-item list, not a diff.
         */
        LineItemInput: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | string;
            /** Unit Price */
            unit_price: number | string;
            /** Total Price */
            total_price: number | string;
        };
        /**
         * LineItemListResponse
         * @description One page of a categorisation-screen view, with what the whole view costs (C3, D1).
         *
         *     `total_amount` covers every matching item across all pages, not just this one,
         *     counted like the month's budget: items on receipts under manual review are
         *     held out and reported in `excluded_*`. `categories` breaks the same items down
         *     per category, ignoring the category filter, so it can be picked from.
         */
        LineItemListResponse: {
            /** Items */
            items: components["schemas"]["ReviewQueueItemResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
            /** Needs Review Count */
            needs_review_count: number;
            /** Total Amount */
            total_amount: string;
            /** Excluded Item Count */
            excluded_item_count: number;
            /** Excluded Amount */
            excluded_amount: string;
            /** Categories */
            categories: components["schemas"]["CategorySpendResponse"][];
        };
        /**
         * LineItemResponse
         * @description Schema for a single line item on a receipt.
         */
        LineItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
            /** Total Price */
            total_price: string;
            /** Category Id */
            category_id: string | null;
            category?: components["schemas"]["CategoryResponse"] | null;
            /** Category Confidence */
            category_confidence?: number | null;
            /**
             * Is Category Manual
             * @default false
             */
            is_category_manual: boolean;
            /**
             * Category Is Low Confidence
             * @description Whether the category needs a human look before it is trusted (BRD C3).
             *
             *     Decided server-side against `Settings.categorization_confidence_threshold`
             *     so the browser renders a verdict instead of recomputing one from a
             *     threshold ADR-0005 says must not be restated at a call site. A category
             *     the owner chose by hand is never flagged, whatever the agent scored (C4).
             */
            readonly category_is_low_confidence: boolean;
        };
        /**
         * LoginRequest
         * @description Payload for authenticating with password (F1.1.4).
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MessageResponse
         * @description Generic message response.
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * MonthSummaryResponse
         * @description One calendar month's spend, as the month view shows it (BRD D1-D3).
         *
         *     `excluded_*` count the receipts held out of `total` because they are under
         *     manual review, and the value of their lines. `is_complete` false means the
         *     figure is month-to-date and must be labelled so (D4), with `days_elapsed` of
         *     `days_in_month` behind it. `finalised_at` is when a finished month's
         *     snapshot was taken; it is null while the month is still running (D5).
         */
        MonthSummaryResponse: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Total */
            total: string;
            /** Receipt Count */
            receipt_count: number;
            /** Has Receipts */
            has_receipts: boolean;
            /** Excluded Count */
            excluded_count: number;
            /** Excluded Amount */
            excluded_amount: string;
            /** Is Complete */
            is_complete: boolean;
            /** Days Elapsed */
            days_elapsed: number;
            /** Days In Month */
            days_in_month: number;
            /** Finalised At */
            finalised_at?: string | null;
        };
        /**
         * PaginatedReceiptsResponse
         * @description Paginated list of receipts.
         */
        PaginatedReceiptsResponse: {
            /** Items */
            items: components["schemas"]["ReceiptResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /**
         * ReceiptDetailResponse
         * @description Schema for a receipt with its full line items.
         */
        ReceiptDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Merchant Name */
            merchant_name: string | null;
            /** Transaction Date */
            transaction_date: string | null;
            /** Total Amount */
            total_amount: string | null;
            /** Status */
            status: string;
            /** File Ids */
            file_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Line Items
             * @default []
             */
            line_items: components["schemas"]["LineItemResponse"][];
        };
        /**
         * ReceiptResponse
         * @description Schema for a receipt list item.
         */
        ReceiptResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Merchant Name */
            merchant_name: string | null;
            /** Transaction Date */
            transaction_date: string | null;
            /** Total Amount */
            total_amount: string | null;
            /** Status */
            status: string;
            /** File Ids */
            file_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Line Items
             * @default []
             */
            line_items: components["schemas"]["LineItemResponse"][];
        };
        /**
         * ReceiptStatus
         * @description Lifecycle states of a receipt.
         * @enum {string}
         */
        ReceiptStatus: "uploaded" | "parsing" | "parsed" | "manual_review" | "failed";
        /**
         * RefreshRequest
         * @description Payload for refreshing an access token (F1.2.3).
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterRequest
         * @description Payload for registering a new account (F1.1.3).
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /**
         * ResolveDuplicateRequest
         * @description Request to resolve a duplicate receipt extraction.
         */
        ResolveDuplicateRequest: {
            /** Extraction Index */
            extraction_index: number;
            /**
             * Action
             * @enum {string}
             */
            action: "store" | "skip";
        };
        /**
         * ResolvePositionMatchRequest
         * @description Request to override an automatic position match decision (BRD B7).
         */
        ResolvePositionMatchRequest: {
            /** Extraction Index */
            extraction_index: number;
            /** Match Index */
            match_index: number;
            /**
             * Action
             * @enum {string}
             */
            action: "same" | "different";
        };
        /**
         * ResolveTotalRequest
         * @description The printed total the user typed for a receipt the parser could not read (BRD A11).
         */
        ResolveTotalRequest: {
            /** Extraction Index */
            extraction_index: number;
            /** Receipt Total */
            receipt_total: string;
        };
        /**
         * ReviewQueueItemResponse
         * @description A line item waiting in the categorisation review queue (BRD C2, C3).
         *
         *     Carries its receipt's merchant and date so the queue can be read without
         *     opening each receipt. The date stays a timestamp: receipts store the
         *     printed time too, and truncating is the browser's formatting decision.
         */
        ReviewQueueItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
            /** Total Price */
            total_price: string;
            /** Category Id */
            category_id: string | null;
            category?: components["schemas"]["CategoryResponse"] | null;
            /** Category Confidence */
            category_confidence?: number | null;
            /**
             * Is Category Manual
             * @default false
             */
            is_category_manual: boolean;
            /**
             * Receipt Id
             * Format: uuid
             */
            receipt_id: string;
            /** Merchant Name */
            merchant_name?: string | null;
            /** Transaction Date */
            transaction_date?: string | null;
            receipt_status: components["schemas"]["ReceiptStatus"];
            /**
             * Category Is Low Confidence
             * @description Whether the category needs a human look before it is trusted (BRD C3).
             *
             *     Decided server-side against `Settings.categorization_confidence_threshold`
             *     so the browser renders a verdict instead of recomputing one from a
             *     threshold ADR-0005 says must not be restated at a call site. A category
             *     the owner chose by hand is never flagged, whatever the agent scored (C4).
             */
            readonly category_is_low_confidence: boolean;
        };
        /**
         * UpdateLineItemCategoryRequest
         * @description Update a line item's category (BRD C4).
         */
        UpdateLineItemCategoryRequest: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /**
             * Apply To Future
             * @default false
             */
            apply_to_future: boolean;
        };
        /**
         * UpdateReceiptRequest
         * @description Correct a stored receipt's header and line items (BRD A9, A11, D6).
         *
         *     Represents the receipt's full desired state, mirroring what the detail
         *     dialog already shows the user — not a partial patch. `total_amount` must
         *     equal the sum of `line_items`' totals, the same invariant enforced when the
         *     receipt was first stored; the two are never allowed to drift apart here
         *     either.
         */
        UpdateReceiptRequest: {
            /** Merchant Name */
            merchant_name: string | null;
            /** Transaction Date */
            transaction_date: string | null;
            /** Total Amount */
            total_amount: number | string;
            /** Line Items */
            line_items: components["schemas"]["LineItemInput"][];
        };
        /**
         * UploadJobStatusResponse
         * @description Current status of an asynchronous receipt upload job.
         *
         *     Once the job completes, ``extracted_data`` contains the structured
         *     extraction output (an ``ExtractedReceipt`` dict) for the "What we read"
         *     wizard screen.
         */
        UploadJobStatusResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /** File Ids */
            file_ids: string[];
            /** Extracted Data */
            extracted_data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Total Items
             * @default 0
             */
            total_items: number;
            /**
             * Processed Items
             * @default 0
             */
            processed_items: number;
        };
        /**
         * UploadReceiptResponse
         * @description Response returned upon successful receipt upload.
         */
        UploadReceiptResponse: {
            /** Message */
            message: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /**
         * UserResponse
         * @description Public representation of a user (F1.1).
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Currency */
            currency: string;
            /** Budget Limit */
            budget_limit?: string | null;
        };
        /**
         * UserUpdateRequest
         * @description Payload for updating user preferences (F1.4).
         */
        UserUpdateRequest: {
            /** Currency */
            currency?: string | null;
            /** Budget Limit */
            budget_limit?: number | string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_users_me_patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_receipt_receipts_upload_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_receipt_receipts_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadReceiptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_receipts_batch_receipts_upload_batch_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    [key: string]: string[];
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadReceiptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_job_status_receipts_upload__job_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_receipt_image_receipts_images__file_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_duplicate_receipts_upload__job_id__resolve_duplicate_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveDuplicateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_position_match_receipts_upload__job_id__resolve_position_match_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolvePositionMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_line_items_receipts_line_items_get: {
        parameters: {
            query?: {
                view?: components["schemas"]["ItemView"];
                q?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                category_id?: string | null;
                page?: number;
                size?: number;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_receipts_receipts_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: components["schemas"]["ReceiptStatus"] | null;
                start_date?: string | null;
                end_date?: string | null;
                q?: string | null;
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReceiptsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_receipt_receipts__receipt_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_receipt_receipts__receipt_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_receipt_receipts__receipt_id__patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReceiptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_total_receipts_upload__job_id__resolve_total_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveTotalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_line_item_receipts_upload__job_id__line_item_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditLineItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_job_receipts_upload__job_id__commit_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_line_item_category_receipts_line_items__item_id__category_patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLineItemCategoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recategorise_receipt_receipts__receipt_id__categorise_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_v1_categories_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_categories__category_id__delete: {
        parameters: {
            query: {
                move_to_id: string;
                token?: string | null;
            };
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_month_summary_api_v1_budget_months__year___month__get: {
        parameters: {
            query?: {
                today?: string | null;
                token?: string | null;
            };
            header?: never;
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
