"""Add progress tracking to UploadJob

Revision ID: 20c1eae2b0d4
Revises: 8cce32737339
Create Date: 2026-09-17 19:11:46.264185

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20c1eae2b0d4"
down_revision: str | Sequence[str] | None = "8cce32737339"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_jobs",
        sa.Column("total_items", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "upload_jobs",
        sa.Column("processed_items", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_jobs", "processed_items")
    op.drop_column("upload_jobs", "total_items")
    # ### end Alembic commands ###
