"""Add channel to receipt

Revision ID: 336ba6a8c5c4
Revises: fa2b2a7fca55
Create Date: 2026-10-08 17:49:05.237137

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "336ba6a8c5c4"
down_revision: str | Sequence[str] | None = "fa2b2a7fca55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    receipt_channel_enum = postgresql.ENUM(
        "PHOTO", "EMAIL", "QR", name="receipt_channel_enum"
    )
    receipt_channel_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipts",
        sa.Column(
            "channel",
            sa.Enum("PHOTO", "EMAIL", "QR", name="receipt_channel_enum"),
            nullable=False,
            server_default="PHOTO",
        ),
    )
    op.add_column("receipts", sa.Column("source_reference", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("receipts", "source_reference")
    op.drop_column("receipts", "channel")
    # ### end Alembic commands ###

    receipt_channel_enum = postgresql.ENUM(
        "PHOTO", "EMAIL", "QR", name="receipt_channel_enum"
    )
    receipt_channel_enum.drop(op.get_bind())
