"""Add PositionMatchOverride

Revision ID: 8cce32737339
Revises: ff4c2cec200b
Create Date: 2026-09-15 19:45:57.111649

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cce32737339"
down_revision: str | Sequence[str] | None = "ff4c2cec200b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position_match_overrides",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_index", sa.Integer(), nullable=False),
        sa.Column("match_index", sa.Integer(), nullable=False),
        sa.Column("original_result", sa.String(), nullable=False),
        sa.Column("corrected_result", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["upload_jobs.id"],
            name=op.f("fk_position_match_overrides_job_id_upload_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_position_match_overrides_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_match_overrides")),
    )
    op.create_index(
        op.f("ix_position_match_overrides_job_id"),
        "position_match_overrides",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_position_match_overrides_user_id"),
        "position_match_overrides",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_position_match_overrides_user_id"), table_name="position_match_overrides"
    )
    op.drop_index(op.f("ix_position_match_overrides_job_id"), table_name="position_match_overrides")
    op.drop_table("position_match_overrides")
    # ### end Alembic commands ###
