"""Add upload_jobs table

Revision ID: 90a2497c4c2f
Revises: cad7752083c7
Create Date: 2026-08-26 18:40:13.228539

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90a2497c4c2f"
down_revision: str | Sequence[str] | None = "cad7752083c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_jobs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="job_status_enum"),
            nullable=False,
        ),
        sa.Column("file_ids", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_upload_jobs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_jobs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upload_jobs")
    op.execute("DROP TYPE job_status_enum")
    # ### end Alembic commands ###
