"""Add is_category_manual to line_items

Revision ID: b0ffcb63fa48
Revises: edf81b4a2774
Create Date: 2026-09-24 19:47:25.510313

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0ffcb63fa48"
down_revision: str | Sequence[str] | None = "edf81b4a2774"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "line_items",
        sa.Column("is_category_manual", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("line_items", "is_category_manual")
    # ### end Alembic commands ###
