"""add_category_confidence_to_line_items

Revision ID: f67084582974
Revises: 52c0c9e1aa13
Create Date: 2026-09-20 17:07:10.310046

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f67084582974"
down_revision: str | Sequence[str] | None = "52c0c9e1aa13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("line_items", sa.Column("category_confidence", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("line_items", "category_confidence")
    # ### end Alembic commands ###
