"""Add feedback to recommendations

Revision ID: fa2b2a7fca55
Revises: a9aa9b83b39d
Create Date: 2026-10-06 18:59:11.586725

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa2b2a7fca55"
down_revision: str | Sequence[str] | None = "a9aa9b83b39d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recommendations",
        sa.Column(
            "feedback",
            sa.Enum(
                "not_helpful", "not_followed", name="feedback_state", native_enum=False, length=16
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendations", "feedback")
    # ### end Alembic commands ###
